import type { Metadata } from "next";
import { Noto_Sans_Display } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Sans_Display({
  subsets: ["cyrillic", "latin"],
  weight: ["300", "400", "500", "600", "700"], // Только нужные веса
  display: "swap",
  variable: "--font-noto",
});

export const metadata: Metadata = {
  title: "MyTop - наш лучший топ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="ru" className={notoSans.variable}>
   <head>
     <link rel="icon" href="/favicon.ico" />
   </head>
   <body>{children}</body>
   </html>
  );
}
